app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, TextAreaField, IntegerField
from wtforms.validators import DataRequired, URL, Email, email_validator
from flask_ckeditor import CKEditorField


class RegisterForm(FlaskForm):
    email = StringField("Email", render_kw={"placeholder": "Email"}, validators=[DataRequired(), Email()])
    password = PasswordField("Password", render_kw={"placeholder": "Password"}, validators=[DataRequired()])
    name = StringField("Name", render_kw={"placeholder": "Full Name"}, validators=[DataRequired()])
    submit = SubmitField("Create Account")


class LoginForm(FlaskForm):
    email = StringField("Email", render_kw={"placeholder": "Email"}, validators=[DataRequired(), Email()])
    password = PasswordField("Password", render_kw={"placeholder": "Password", "cols": "5"}, validators=[
        DataRequired()])
    submit = SubmitField("Create Account")


class ChangeEmailForm(FlaskForm):
    password = PasswordField("Current Password", validators=[DataRequired()])
    email = StringField("Edit Email", validators=[DataRequired(), Email()])
    submit = SubmitField("Change Email")


class ChangePasswordForm(FlaskForm):
    current_password = PasswordField("Current Password", validators=[DataRequired()])
    new_password = PasswordField("New Password", validators=[DataRequired()])
    submit = SubmitField("Change Password")

app/__init__.py
from flask_bootstrap import Bootstrap
from flask_debugtoolbar import DebugToolbarExtension
from flask_login import LoginManager
from app.tables import db, User
import os
from flask import Flask
from app.routes import app_index, app_accounts

# App Init
app = Flask(__name__)
app.config['SECRET_KEY'] = '8BYkEfBA6O6donzWlSihBXox7C0sKR6b'
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///stretch-timer.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['DEBUG_TB_INTERCEPT_REDIRECTS'] = False
# Database Init
db.init_app(app)
# TODO: Hide app config in environment variable
# app.config.from_object(os.environ['APP_SETTINGS'])

# Debugger toolbar
app.debug = True
toolbar = DebugToolbarExtension(app)

# CK EDITOR for advanced text field form input  field
# ckeditor = CKEditor(app)
# Bootstrap html integration
Bootstrap(app)

# Following logged user status
login_manager = LoginManager()
login_manager.init_app(app)

# App routes blueprints
app.register_blueprint(app_index)
app.register_blueprint(app_accounts)

# Create all tables imported from app.tables
# TODO: Add Database Migration.
with app.app_context():
    db.create_all()


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

app/routes.py
# Flask useful routes functions
import time

from flask import flash, render_template, redirect, url_for, abort, Blueprint, Response, request, jsonify
# For random user image
from flask_gravatar import Gravatar
# Managing logged in Users status
from flask_login import login_user, login_required, current_user, logout_user
# Password Security
from werkzeug.security import generate_password_hash, check_password_hash
# FORMS
from app.forms import RegisterForm, LoginForm
# Database Tables Managing with SQLAlchemy
from app.tables import User, db
# Decorators
from app.decorators import admin_only

# gravatar = Gravatar(app, size=100, rating='g', default='retro', force_default=False, force_lower=False,
#                     use_ssl=False,
#                     base_url=None)

app_index = Blueprint('index_route', __name__,
                      template_folder='templates')
app_accounts = Blueprint('accounts_route', __name__,
                         template_folder='templates/accounts')


# Index Route
@app_index.route('/')
def home():
    return render_template('index.html')


@app_index.route('/about')
def about():
    return render_template('about.html')


@app_accounts.route('/user-settings', methods=['GET', 'POST'])
@login_required
def user_settings():
    return render_template('user-settings.html')


@app_accounts.route('/register', methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        email = form.email.data
        if User.query.filter_by(email=email).first():
            flash("Email already exists. Try to log in.")
            return redirect(url_for("accounts_route.login"))
        password = generate_password_hash(form.password.data, salt_length=8)
        name = form.name.data
        new_user = User(email=email, password=password, name=name)
        db.session.add(new_user)
        db.session.commit()
        login_user(User.query.filter_by(email=email).first())
        return redirect(url_for("index_route.home"))
    return render_template("register.html", form=form)


@app_accounts.route('/login', methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        user = User.query.filter_by(email=email).first()
        if not user:
            flash("Unknown Email, Try Again.")
            return render_template("login.html", form=form)
        password = form.password.data
        if not check_password_hash(user.password, password):
            flash("Wrong Password, Try Again.")
            return render_template("login.html", form=form)
        login_user(user)
        return redirect(url_for("index_route.home"))
    return render_template("login.html", form=form)


@app_accounts.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index_route.home'))

app/templates/about.html
{% extends 'bootstrap/base.html' %}
{% block content %}
    {% include "includes/header.html" %}

    <!-- Page Header -->
    <header class="masthead" style="background-image: url({{ url_for('static', filename='img/about-bg.jpg') }})">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="page-heading">
                        <h1>About Us</h1>
                        <span class="subheading">This is what we do.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur
                    voluptates
                    odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus
                    consectetur?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque
                    architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum
                    in
                    officia voluptas voluptatibus, minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid
                    ex
                    itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit
                    tempora!</p>
            </div>
        </div>
    </div>

    <hr>

    {% include "includes/footer.html" %}
{% endblock %}

app/templates/accounts/login.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    {% include "includes/header.html" %}

    <!-- Page Header -->
    <header class="masthead"
            style="background-image: url('https://images.unsplash.com/photo-1484100356142-db6ab6244067?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="page-heading">
                        <h1>Log In</h1>
                        <span class="subheading">Welcome Back!</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <p>{{ message }}</p>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            <div class="col-lg-8 col-md-10 mx-auto content" style="width: 25%">
                {{ wtf.quick_form(form, novalidate=True, button_map={"submit": "primary"}) }}
            </div>
        </div>
    </div>


    {% include "includes/footer.html" %}
{% endblock %}

app/templates/accounts/register.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
    {% include "includes/header.html" %}

    <!-- Page Header -->
    <header class="masthead"
            style="background-image: url('https://images.unsplash.com/photo-1531592937781-344ad608fabf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80')">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="page-heading">
                        <h1>Register</h1>
                        <h5>Get Better Tailored Experience!</h5>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto content" style="width: 25%">
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        {% for message in messages %}
                            <p>{{ message }}</p>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
                {{ wtf.quick_form(form, novalidate=True, button_map={"submit": "primary"}) }}
            </div>
            {#        <div class="col-lg-8 col-md-10 mx-auto">#}
            {#            <div class="input-group">#}
            {#                <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>#}
            {#                {{ form.email(placeholder="name@example.com", class_="form-control") }}#}
            {#            </div>#}
            {#            <div class="input-group">#}
            {#                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>#}
            {#                {{ form.password(placeholder="Password", class_="form-control") }}#}
            {#            </div>#}
            {#            <div class="input-group">#}
            {#                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>#}
            {#                {{ form.name() }}#}
            {#            </div>#}
            {#            {{ form.submit() }}#}

        </div>
    </div>

    {% include "includes/footer.html" %}
{% endblock %}

app/templates/bootstrap/base.html
{% block doc -%}
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
  <head>
    {%- block head %}
    <title>{% block title %}{{title|default}}{% endblock title %}</title>

    {%- block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%- endblock metas %}

    {%- block styles %}
    <!-- Bootstrap -->
    <link href="{{bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap')}}" rel="stylesheet">
    {%- endblock styles %}
    {%- endblock head %}
  </head>
  <body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}
    {% block navbar %}
    {%- endblock navbar %}
    {% block content -%}
    {%- endblock content %}

    {% block scripts %}
    <script src="{{bootstrap_find_resource('jquery.js', cdn='jquery')}}"></script>
    <script src="{{bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap')}}"></script>
    {%- endblock scripts %}
    {%- endblock body %}
  </body>
{%- endblock html %}
</html>
{% endblock doc -%}

app/templates/bootstrap/fixes.html
{% macro ie8() %}
    <!--[if lt IE 9]>
          <script src="{{bootstrap_find_resource('html5shiv.js', cdn='html5shiv', local=False)}}"></script>
          <script src="{{bootstrap_find_resource('respond.js', cdn='respond.js', local=False)}}"></script>
    <![endif]-->
{% endmacro %}

app/templates/bootstrap/google.html
{% macro analytics(account) -%}
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '{{account}}']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
{% endmacro %}

{% macro uanalytics(id, options='auto', domain=None) %}
{# The uanalytics macro currently contains a hack to support legacy code.
   The old signature was ``uanalytics(id, domain)`` when domain was a required
   parameter that was passed on to the ga() function.

   To preserve old behavior, if options is not a dictionary, it is passed on
   unchanged. The ``domain`` parameter is added to not break calls with named
   parameters, it will override any other value for options.

   More modern code can simply pass any desired option to the analytics
   function as desired.
#}
{%- if domain != None %}
{%- set options = domain %}
{%- endif %}
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', {{id|tojson|safe}}, {{options|tojson|safe}});
  ga('send', 'pageview');
</script>
{% endmacro %}

app/templates/bootstrap/pagination.html
{% macro _arg_url_for(endpoint, base) %}
{# calls url_for() with a given endpoint and **base as the parameters,
   additionally passing on all keyword_arguments (may overwrite existing ones)
 #}
{%- with kargs = base.copy() -%}
{%- do kargs.update(kwargs) -%}
{{url_for(endpoint, **kargs)}}
{%- endwith %}
{%- endmacro %}

{% macro render_pagination(pagination,
                           endpoint=None,
                           prev=('&laquo;')|safe,
                           next=('&raquo;')|safe,
                           size=None,
                           ellipses='…',
                           args={}
                           )
-%}
{% with url_args = {} %}
{%- do url_args.update(request.view_args if not endpoint else {}),
       url_args.update(request.args if not endpoint else {}),
       url_args.update(args) -%}
{% with endpoint = endpoint or request.endpoint %}
<nav>
  <ul class="pagination{% if size %} pagination-{{size}}{% endif %}"{{kwargs|xmlattr}}>
  {# prev and next are only show if a symbol has been passed. #}
  {% if prev != None -%}
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}><a href="{{_arg_url_for(endpoint, url_args, page=pagination.prev_num) if pagination.has_prev else '#'}}">{{prev}}</a></li>
  {%- endif -%}

  {%- for page in pagination.iter_pages() %}
    {% if page %}
      {% if page != pagination.page %}
        <li><a href="{{_arg_url_for(endpoint, url_args, page=page)}}">{{page}}</a></li>
      {% else %}
        <li class="active"><a href="#">{{page}} <span class="sr-only">(current)</span></a></li>
      {% endif %}
    {% elif ellipses != None %}
      <li class="disabled"><a href="#">{{ellipses}}</a></li>
    {% endif %}
  {%- endfor %}

  {% if next != None -%}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}><a href="{{_arg_url_for(endpoint, url_args, page=pagination.next_num) if pagination.has_next else '#'}}">{{next}}</a></li>
  {%- endif -%}
  </ul>
</nav>
{% endwith %}
{% endwith %}
{% endmacro %}

app/templates/bootstrap/utils.html
{% macro flashed_messages(messages=None, container=True, transform={
  'critical': 'danger',
  'error': 'danger',
  'info': 'info',
  'warning': 'warning',
  'debug': 'info',
  'notset': 'info',
  'message': 'info',
}, default_category=None, dismissible=False) -%}
{% with messages = messages or get_flashed_messages(with_categories=True) -%}
{% if messages -%} {# don't output anything if there are no messages #}

{% if container -%}
<!-- begin message block -->
<div class="container flashed-messages">
  <div class="row">
    <div class="col-md-12">
{% endif -%}

{% for cat, msg in messages %}      <div class="alert alert-{{transform.get(cat.lower(), default_category or cat)}}{% if dismissible %} alert-dismissible{% endif %}" role="alert">
{% if dismissible %}        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{% endif %}
        {{msg}}
      </div>
{%- endfor -%}

{% if container %}
    </div>
  </div>
</div>
<!-- end message block -->
{% endif -%}

{% endif -%}
{% endwith -%}
{% endmacro -%}


{% macro icon(type=None, extra_classes=[]) -%}
<span{{ ({'class': (['glyphicon', 'glyphicon-' + type] + extra_classes)|join(' ')})|xmlattr}}{{kwargs|xmlattr}}></span>
{%- endmacro %}


{% macro form_button(url, content, method='post', class='btn-link') -%}
<form style="display: inline;" action='{{url}}' method='{{method}}'><button class="{{class|safe}}">{{content}}</button></form>
{%- endmacro %}

app/templates/bootstrap/wtf.html
{% macro form_errors(form, hiddens=True) %}
  {%- if form.errors %}
    {%- for fieldname, errors in form.errors.items() %}
      {%- if bootstrap_is_hidden_field(form[fieldname]) and hiddens or
             not bootstrap_is_hidden_field(form[fieldname]) and hiddens != 'only' %}
        {%- for error in errors %}
          <p class="error">{{error}}</p>
        {%- endfor %}
      {%- endif %}
    {%- endfor %}
  {%- endif %}
{%- endmacro %}

{% macro _hz_form_wrap(horizontal_columns, form_type, add_group=False, required=False) %}
{% if form_type == "horizontal" %}
  {% if add_group %}<div class="form-group{% if required %} required{% endif %}">{% endif %}
  <div class="col-{{horizontal_columns[0]}}-offset-{{horizontal_columns[1]}}
              col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}
             ">
{% endif %}
{{caller()}}

{% if form_type == "horizontal" %}
  {% if add_group %}</div>{% endif %}
  </div>
{% endif %}
{% endmacro %}

{% macro form_field(field,
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    button_map={}) %}

{# this is a workaround hack for the more straightforward-code of just passing required=required parameter. older versions of wtforms do not have
the necessary fix for required=False attributes, but will also not set the required flag in the first place. we skirt the issue using the code below #}
{% if field.flags.required and not required in kwargs %}
{% set kwargs = dict(required=True, **kwargs) %}
{% endif %}

{% if field.widget.input_type == 'checkbox' %}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    <div class="checkbox">
      <label>
        {{field()|safe}} {{field.label.text|safe}}
      </label>
    </div>
  {% endcall %}
{%- elif field.type == 'RadioField' -%}
  {# note: A cleaner solution would be rendering depending on the widget,
     this is just a hack for now, until I can think of something better #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    {% for item in field -%}
      <div class="radio">
        <label>
          {{item|safe}} {{item.label.text|safe}}
        </label>
      </div>
    {% endfor %}
  {% endcall %}
{%- elif field.type == 'SubmitField' -%}
  {# deal with jinja scoping issues? #}
  {% set field_kwargs = kwargs %}

  {# note: same issue as above - should check widget, not field type #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    {{field(class='btn btn-%s' % button_map.get(field.name, 'default'),
            **field_kwargs)}}
  {% endcall %}
{%- elif field.type == 'FormField' -%}
{# note: FormFields are tricky to get right and complex setups requiring
   these are probably beyond the scope of what this macro tries to do.
   the code below ensures that things don't break horribly if we run into
   one, but does not try too hard to get things pretty. #}
  <fieldset>
    <legend>{{field.label}}</legend>
    {%- for subfield in field %}
      {% if not bootstrap_is_hidden_field(subfield) -%}
        {{ form_field(subfield,
                      form_type=form_type,
                      horizontal_columns=horizontal_columns,
                      button_map=button_map) }}
      {%- endif %}
    {%- endfor %}
  </fieldset>
{% else -%}
  <div class="form-group {% if field.errors %} has-error{% endif -%}
                         {%- if field.flags.required %} required{% endif -%}
  ">
      {%- if form_type == "inline" %}
        {{field.label(class="sr-only")|safe}}
        {% if field.type == 'FileField' %}
          {{field(**kwargs)|safe}}
        {% else %}
          {{field(class="form-control", **kwargs)|safe}}
        {% endif %}
      {% elif form_type == "horizontal" %}
        {{field.label(class="control-label " + (
          " col-%s-%s" % horizontal_columns[0:2]
        ))|safe}}
        <div class=" col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}">
          {% if field.type == 'FileField' %}
            {{field(**kwargs)|safe}}
          {% else %}
            {{field(class="form-control", **kwargs)|safe}}
          {% endif %}
        </div>
        {%- if field.errors %}
          {%- for error in field.errors %}
            {% call _hz_form_wrap(horizontal_columns, form_type, required=required) %}
              <p class="help-block">{{error}}</p>
            {% endcall %}
          {%- endfor %}
        {%- elif field.description -%}
          {% call _hz_form_wrap(horizontal_columns, form_type, required=required) %}
            <p class="help-block">{{field.description|safe}}</p>
          {% endcall %}
        {%- endif %}
      {%- else -%}
        {{field.label(class="control-label")|safe}}
        {% if field.type == 'FileField' %}
          {{field(**kwargs)|safe}}
        {% else %}
          {{field(class="form-control", **kwargs)|safe}}
        {% endif %}

        {%- if field.errors %}
          {%- for error in field.errors %}
            <p class="help-block">{{error}}</p>
          {%- endfor %}
        {%- elif field.description -%}
          <p class="help-block">{{field.description|safe}}</p>
        {%- endif %}
      {%- endif %}
  </div>
{% endif %}
{% endmacro %}

{# valid form types are "basic", "inline" and "horizontal" #}
{% macro quick_form(form,
                    action="",
                    method="post",
                    extra_classes=None,
                    role="form",
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    enctype=None,
                    button_map={},
                    id="",
                    novalidate=False,
                    render_kw={}) %}
{#-
action="" is what we want, from http://www.ietf.org/rfc/rfc2396.txt:

4.2. Same-document References

   A URI reference that does not contain a URI is a reference to the
   current document.  In other words, an empty URI reference within a
   document is interpreted as a reference to the start of that document,
   and a reference containing only a fragment identifier is a reference
   to the identified fragment of that document.  Traversal of such a
   reference should not result in an additional retrieval action.
   However, if the URI reference occurs in a context that is always
   intended to result in a new request, as in the case of HTML's FORM
   element, then an empty URI reference represents the base URI of the
   current document and should be replaced by that URI when transformed
   into a request.

 -#}
{#- if any file fields are inside the form and enctype is automatic, adjust
    if file fields are found. could really use the equalto test of jinja2
    here, but latter is not available until 2.8

    warning: the code below is guaranteed to make you cry =(
#}
{%- set _enctype = [] %}
{%- if enctype is none -%}
  {%- for field in form %}
    {%- if field.type == 'FileField' %}
      {#- for loops come with a fairly watertight scope, so this list-hack is
          used to be able to set values outside of it #}
      {%- set _ = _enctype.append('multipart/form-data') -%}
    {%- endif %}
  {%- endfor %}
{%- else %}
  {% set _ = _enctype.append(enctype) %}
{%- endif %}
<form
  {%- if action != None %} action="{{action}}"{% endif -%}
  {%- if id %} id="{{id}}"{% endif -%}
  {%- if method %} method="{{method}}"{% endif %}
  class="form
    {%- if extra_classes %} {{extra_classes}}{% endif -%}
    {%- if form_type == "horizontal" %} form-horizontal
    {%- elif form_type == "inline" %} form-inline
    {%- endif -%}
  "
  {%- if _enctype[0] %} enctype="{{_enctype[0]}}"{% endif -%}
  {%- if role %} role="{{role}}"{% endif -%}
  {%- if novalidate %} novalidate{% endif -%}
  {%- if render_kw %} {{render_kw|xmlattr}}{% endif -%}
  >
  {{ form.hidden_tag() }}
  {{ form_errors(form, hiddens='only') }}

  {%- for field in form %}
    {% if not bootstrap_is_hidden_field(field) -%}
      {{ form_field(field,
                    form_type=form_type,
                    horizontal_columns=horizontal_columns,
                    button_map=button_map) }}
    {%- endif %}
  {%- endfor %}

</form>
{%- endmacro %}

app/templates/includes/footer.html
<!-- Footer -->
<br>
<br>
<br>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <p class="copyright text-muted">Copyright &copy; StretchTimer 2023</p>
                    </li>
                    <li class="list-inline-item">
                        <a href="https://github.com/mariamnersisyan97/StretchTimer">
                            <span class="fa-stack fa-lg">
                              <i class="fas fa-circle fa-stack-2x"></i>
                              <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>

            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/main.js') }}"></script>


</body>

</html>

app/templates/includes/header.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>StretchTimer</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Orbitron' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Pacifico|Open+Sans:300' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <!-- Custom fonts for this template -->
    <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet"
          type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-inverse" id="mainNav">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{ url_for('index_route.home') }}">StretchTimer</a>
        </div>
        <ul class="nav navbar-nav">
            <li class="active">
                <a href="{{ url_for('index_route.home') }}">Home</a>
            </li>
            <li>
                <a href="{{ url_for('index_route.about') }}">
                    About Us</a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            {% if not current_user.is_authenticated %}
                <li>
                    <a href="{{ url_for('accounts_route.login') }}"><span class="glyphicon glyphicon-user"></span>
                        Login</a>
                </li>
                <li>
                    <a href="{{ url_for('accounts_route.register') }}"><span class="glyphicon
                    glyphicon-log-in"></span> Register</a>
                </li>
            {% else %}
                <li>
                    <a href="{{ url_for('accounts_route.user_settings') }}"><span class="glyphicon
                    glyphicon-user"></span>
                        Hi {{ current_user.name }}</a>
                </li>
                <li>
                    <a href="{{ url_for('accounts_route.logout') }}"><span class="glyphicon glyphicon-log-out"></span>
                        Log Out</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>